#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("InstaFollow.Resource", IsApplication=true)]

namespace InstaFollow
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010009
			public const int alpha = 2130771977;
			
			// aapt resource value: 0x7f010016
			public const int civ_border_color = 2130771990;
			
			// aapt resource value: 0x7f010017
			public const int civ_border_overlay = 2130771991;
			
			// aapt resource value: 0x7f010015
			public const int civ_border_width = 2130771989;
			
			// aapt resource value: 0x7f010018
			public const int civ_fill_color = 2130771992;
			
			// aapt resource value: 0x7f010000
			public const int coordinatorLayoutStyle = 2130771968;
			
			// aapt resource value: 0x7f010011
			public const int font = 2130771985;
			
			// aapt resource value: 0x7f01000a
			public const int fontProviderAuthority = 2130771978;
			
			// aapt resource value: 0x7f01000d
			public const int fontProviderCerts = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int fontProviderFetchStrategy = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int fontProviderFetchTimeout = 2130771983;
			
			// aapt resource value: 0x7f01000b
			public const int fontProviderPackage = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int fontProviderQuery = 2130771980;
			
			// aapt resource value: 0x7f010010
			public const int fontStyle = 2130771984;
			
			// aapt resource value: 0x7f010013
			public const int fontVariationSettings = 2130771987;
			
			// aapt resource value: 0x7f010012
			public const int fontWeight = 2130771986;
			
			// aapt resource value: 0x7f010001
			public const int keylines = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int layout_anchor = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int layout_anchorGravity = 2130771974;
			
			// aapt resource value: 0x7f010003
			public const int layout_behavior = 2130771971;
			
			// aapt resource value: 0x7f010008
			public const int layout_dodgeInsetEdges = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int layout_insetEdge = 2130771975;
			
			// aapt resource value: 0x7f010005
			public const int layout_keyline = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int statusBarBackground = 2130771970;
			
			// aapt resource value: 0x7f010014
			public const int ttcIndex = 2130771988;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f05000b
			public const int AliceBlue = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int AntiqueWhite = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int Aqua = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int Aquamarine = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int Azure = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int Beige = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int Bisque = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int Black = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int BlanchedAlmond = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int Blue = 2131034132;
			
			// aapt resource value: 0x7f050009
			public const int BlueFollow = 2131034121;
			
			// aapt resource value: 0x7f050015
			public const int BlueViolet = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int Brown = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int BurlyWood = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int CadetBlue = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int Chartreuse = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int Chocolate = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int Coral = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int CornflowerBlue = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int Cornsilk = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int Crimson = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int Cyan = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int DarkBlue = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int DarkCyan = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int DarkGoldenrod = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int DarkGray = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int DarkGreen = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int DarkKhaki = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int DarkMagenta = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int DarkOliveGreen = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int DarkOrange = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int DarkOrchid = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int DarkRed = 2131034154;
			
			// aapt resource value: 0x7f05002b
			public const int DarkSalmon = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int DarkSeaGreen = 2131034156;
			
			// aapt resource value: 0x7f05002d
			public const int DarkSlateBlue = 2131034157;
			
			// aapt resource value: 0x7f05002e
			public const int DarkSlateGray = 2131034158;
			
			// aapt resource value: 0x7f05002f
			public const int DarkTurquoise = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int DarkViolet = 2131034160;
			
			// aapt resource value: 0x7f050031
			public const int DeepPink = 2131034161;
			
			// aapt resource value: 0x7f050032
			public const int DeepSkyBlue = 2131034162;
			
			// aapt resource value: 0x7f050033
			public const int DimGray = 2131034163;
			
			// aapt resource value: 0x7f050034
			public const int DodgerBlue = 2131034164;
			
			// aapt resource value: 0x7f050035
			public const int Firebrick = 2131034165;
			
			// aapt resource value: 0x7f050036
			public const int FloralWhite = 2131034166;
			
			// aapt resource value: 0x7f050037
			public const int ForestGreen = 2131034167;
			
			// aapt resource value: 0x7f050038
			public const int Fuchsia = 2131034168;
			
			// aapt resource value: 0x7f050039
			public const int Gainsboro = 2131034169;
			
			// aapt resource value: 0x7f05003a
			public const int GhostWhite = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int Gold = 2131034171;
			
			// aapt resource value: 0x7f05003c
			public const int Goldenrod = 2131034172;
			
			// aapt resource value: 0x7f05003d
			public const int Gray = 2131034173;
			
			// aapt resource value: 0x7f05003e
			public const int Green = 2131034174;
			
			// aapt resource value: 0x7f05003f
			public const int GreenYellow = 2131034175;
			
			// aapt resource value: 0x7f050040
			public const int Honeydew = 2131034176;
			
			// aapt resource value: 0x7f050041
			public const int HotPink = 2131034177;
			
			// aapt resource value: 0x7f050042
			public const int IndianRed = 2131034178;
			
			// aapt resource value: 0x7f050043
			public const int Indigo = 2131034179;
			
			// aapt resource value: 0x7f050044
			public const int Ivory = 2131034180;
			
			// aapt resource value: 0x7f050045
			public const int Khaki = 2131034181;
			
			// aapt resource value: 0x7f050046
			public const int Lavender = 2131034182;
			
			// aapt resource value: 0x7f050047
			public const int LavenderBlush = 2131034183;
			
			// aapt resource value: 0x7f050048
			public const int LawnGreen = 2131034184;
			
			// aapt resource value: 0x7f050049
			public const int LemonChiffon = 2131034185;
			
			// aapt resource value: 0x7f05004a
			public const int LightBlue = 2131034186;
			
			// aapt resource value: 0x7f05004b
			public const int LightCoral = 2131034187;
			
			// aapt resource value: 0x7f05004c
			public const int LightCyan = 2131034188;
			
			// aapt resource value: 0x7f05004d
			public const int LightGoldenrodYellow = 2131034189;
			
			// aapt resource value: 0x7f05004e
			public const int LightGray = 2131034190;
			
			// aapt resource value: 0x7f05004f
			public const int LightGreen = 2131034191;
			
			// aapt resource value: 0x7f050050
			public const int LightPink = 2131034192;
			
			// aapt resource value: 0x7f050051
			public const int LightSalmon = 2131034193;
			
			// aapt resource value: 0x7f050052
			public const int LightSeaGreen = 2131034194;
			
			// aapt resource value: 0x7f050053
			public const int LightSkyBlue = 2131034195;
			
			// aapt resource value: 0x7f050054
			public const int LightSlateGray = 2131034196;
			
			// aapt resource value: 0x7f050055
			public const int LightSteelBlue = 2131034197;
			
			// aapt resource value: 0x7f050056
			public const int LightYellow = 2131034198;
			
			// aapt resource value: 0x7f050057
			public const int Lime = 2131034199;
			
			// aapt resource value: 0x7f050058
			public const int LimeGreen = 2131034200;
			
			// aapt resource value: 0x7f050059
			public const int Linen = 2131034201;
			
			// aapt resource value: 0x7f05005a
			public const int Magenta = 2131034202;
			
			// aapt resource value: 0x7f05005b
			public const int Maroon = 2131034203;
			
			// aapt resource value: 0x7f05005c
			public const int MediumAquamarine = 2131034204;
			
			// aapt resource value: 0x7f05005d
			public const int MediumBlue = 2131034205;
			
			// aapt resource value: 0x7f05005e
			public const int MediumOrchid = 2131034206;
			
			// aapt resource value: 0x7f05005f
			public const int MediumPurple = 2131034207;
			
			// aapt resource value: 0x7f050060
			public const int MediumSeaGreen = 2131034208;
			
			// aapt resource value: 0x7f050061
			public const int MediumSlateBlue = 2131034209;
			
			// aapt resource value: 0x7f050062
			public const int MediumSpringGreen = 2131034210;
			
			// aapt resource value: 0x7f050063
			public const int MediumTurquoise = 2131034211;
			
			// aapt resource value: 0x7f050064
			public const int MediumVioletRed = 2131034212;
			
			// aapt resource value: 0x7f050065
			public const int MidnightBlue = 2131034213;
			
			// aapt resource value: 0x7f050066
			public const int MintCream = 2131034214;
			
			// aapt resource value: 0x7f050067
			public const int MistyRose = 2131034215;
			
			// aapt resource value: 0x7f050068
			public const int Moccasin = 2131034216;
			
			// aapt resource value: 0x7f050007
			public const int MyApplicationBlackColor = 2131034119;
			
			// aapt resource value: 0x7f050069
			public const int NavajoWhite = 2131034217;
			
			// aapt resource value: 0x7f05006a
			public const int Navy = 2131034218;
			
			// aapt resource value: 0x7f05006b
			public const int OldLace = 2131034219;
			
			// aapt resource value: 0x7f05006c
			public const int Olive = 2131034220;
			
			// aapt resource value: 0x7f05006d
			public const int OliveDrab = 2131034221;
			
			// aapt resource value: 0x7f05006e
			public const int Orange = 2131034222;
			
			// aapt resource value: 0x7f05006f
			public const int OrangeRed = 2131034223;
			
			// aapt resource value: 0x7f050070
			public const int Orchid = 2131034224;
			
			// aapt resource value: 0x7f050071
			public const int PaleGoldenrod = 2131034225;
			
			// aapt resource value: 0x7f050072
			public const int PaleGreen = 2131034226;
			
			// aapt resource value: 0x7f050073
			public const int PaleTurquoise = 2131034227;
			
			// aapt resource value: 0x7f050074
			public const int PaleVioletRed = 2131034228;
			
			// aapt resource value: 0x7f050075
			public const int PapayaWhip = 2131034229;
			
			// aapt resource value: 0x7f050076
			public const int PeachPuff = 2131034230;
			
			// aapt resource value: 0x7f050077
			public const int Peru = 2131034231;
			
			// aapt resource value: 0x7f050078
			public const int Pink = 2131034232;
			
			// aapt resource value: 0x7f050079
			public const int Plum = 2131034233;
			
			// aapt resource value: 0x7f05007a
			public const int PowderBlue = 2131034234;
			
			// aapt resource value: 0x7f05007b
			public const int Purple = 2131034235;
			
			// aapt resource value: 0x7f05007c
			public const int Red = 2131034236;
			
			// aapt resource value: 0x7f050008
			public const int RedUnfollow = 2131034120;
			
			// aapt resource value: 0x7f05007d
			public const int RosyBrown = 2131034237;
			
			// aapt resource value: 0x7f05007e
			public const int RoyalBlue = 2131034238;
			
			// aapt resource value: 0x7f05007f
			public const int SaddleBrown = 2131034239;
			
			// aapt resource value: 0x7f050080
			public const int Salmon = 2131034240;
			
			// aapt resource value: 0x7f050081
			public const int SandyBrown = 2131034241;
			
			// aapt resource value: 0x7f050082
			public const int SeaGreen = 2131034242;
			
			// aapt resource value: 0x7f050083
			public const int SeaShell = 2131034243;
			
			// aapt resource value: 0x7f050084
			public const int Sienna = 2131034244;
			
			// aapt resource value: 0x7f050085
			public const int Silver = 2131034245;
			
			// aapt resource value: 0x7f050086
			public const int SkyBlue = 2131034246;
			
			// aapt resource value: 0x7f050087
			public const int SlateBlue = 2131034247;
			
			// aapt resource value: 0x7f050088
			public const int SlateGray = 2131034248;
			
			// aapt resource value: 0x7f050089
			public const int Snow = 2131034249;
			
			// aapt resource value: 0x7f05008a
			public const int SpringGreen = 2131034250;
			
			// aapt resource value: 0x7f05008b
			public const int SteelBlue = 2131034251;
			
			// aapt resource value: 0x7f05008c
			public const int Tan = 2131034252;
			
			// aapt resource value: 0x7f05008d
			public const int Teal = 2131034253;
			
			// aapt resource value: 0x7f05008e
			public const int Thistle = 2131034254;
			
			// aapt resource value: 0x7f05008f
			public const int Tomato = 2131034255;
			
			// aapt resource value: 0x7f05000a
			public const int Transparent = 2131034122;
			
			// aapt resource value: 0x7f050090
			public const int Turquoise = 2131034256;
			
			// aapt resource value: 0x7f050091
			public const int Violet = 2131034257;
			
			// aapt resource value: 0x7f050092
			public const int Wheat = 2131034258;
			
			// aapt resource value: 0x7f050093
			public const int White = 2131034259;
			
			// aapt resource value: 0x7f050094
			public const int WhiteSmoke = 2131034260;
			
			// aapt resource value: 0x7f050095
			public const int Yellow = 2131034261;
			
			// aapt resource value: 0x7f050096
			public const int YellowGreen = 2131034262;
			
			// aapt resource value: 0x7f050003
			public const int notification_action_color_filter = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int notification_icon_bg_color = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int notification_material_background_media_default_color = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int primary_text_default_material_dark = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int ripple_material_light = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int secondary_text_default_material_dark = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int secondary_text_default_material_light = 2131034118;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060008
			public const int compat_button_inset_horizontal_material = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int compat_button_inset_vertical_material = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int compat_button_padding_horizontal_material = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int compat_button_padding_vertical_material = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int compat_control_corner_material = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int compat_notification_large_icon_max_height = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int compat_notification_large_icon_max_width = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int notification_action_icon_size = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int notification_action_text_size = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int notification_big_circle_margin = 2131099665;
			
			// aapt resource value: 0x7f060005
			public const int notification_content_margin_start = 2131099653;
			
			// aapt resource value: 0x7f060012
			public const int notification_large_icon_height = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int notification_large_icon_width = 2131099667;
			
			// aapt resource value: 0x7f060006
			public const int notification_main_column_padding_top = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int notification_media_narrow_margin = 2131099655;
			
			// aapt resource value: 0x7f060014
			public const int notification_right_icon_size = 2131099668;
			
			// aapt resource value: 0x7f060004
			public const int notification_right_side_padding_top = 2131099652;
			
			// aapt resource value: 0x7f060015
			public const int notification_small_icon_background_padding = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int notification_small_icon_size_as_large = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int notification_subtext_size = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int notification_top_pad = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int notification_top_pad_large_text = 2131099673;
			
			// aapt resource value: 0x7f060000
			public const int subtitle_corner_radius = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int subtitle_outline_width = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int subtitle_shadow_offset = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int subtitle_shadow_radius = 2131099651;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Accounts_Header = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Custom_Add_Button = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Custom_Add_Button_Pressed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Custom_Back_Button = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Custom_Delete_Button = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Custom_Delete_Button_Pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Custom_Next = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int CustomAddButton = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int CustomBackButton = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int CustomBorder = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int CustomBorderAccounts = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int CustomBorderFollowsListBlue = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int CustomBorderFollowsListRed = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int CustomBorderForImageView = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int CustomBorderMain = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int CustomBorderMainOrange = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int CustomBorderMinProfileOrange3dp = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int CustomBorderOrange = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int CustomDeleteButton = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Flat_User_Avatar = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Horizontal_Separator = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Icon = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ninepatch_border_blue = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ninepatch_border_orange = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int notification_action_background = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int notification_bg = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int notification_bg_low = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int notification_bg_low_normal = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int notification_bg_low_pressed = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int notification_bg_normal = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int notification_bg_normal_pressed = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int notification_icon_background = 2130837535;
			
			// aapt resource value: 0x7f020022
			public const int notification_template_icon_bg = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int notification_template_icon_low_bg = 2130837539;
			
			// aapt resource value: 0x7f020020
			public const int notification_tile_bg = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int notify_panel_notification_icon_bg = 2130837537;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090032
			public const int LoginWebView = 2131296306;
			
			// aapt resource value: 0x7f090021
			public const int MainBody = 2131296289;
			
			// aapt resource value: 0x7f09001d
			public const int NavBar = 2131296285;
			
			// aapt resource value: 0x7f090059
			public const int action0 = 2131296345;
			
			// aapt resource value: 0x7f090056
			public const int action_container = 2131296342;
			
			// aapt resource value: 0x7f09005d
			public const int action_divider = 2131296349;
			
			// aapt resource value: 0x7f090057
			public const int action_image = 2131296343;
			
			// aapt resource value: 0x7f090058
			public const int action_text = 2131296344;
			
			// aapt resource value: 0x7f090067
			public const int actions = 2131296359;
			
			// aapt resource value: 0x7f090017
			public const int all = 2131296279;
			
			// aapt resource value: 0x7f090018
			public const int async = 2131296280;
			
			// aapt resource value: 0x7f090019
			public const int blocking = 2131296281;
			
			// aapt resource value: 0x7f090008
			public const int bottom = 2131296264;
			
			// aapt resource value: 0x7f090027
			public const int btnAccountDelete = 2131296295;
			
			// aapt resource value: 0x7f090033
			public const int btnAccounts = 2131296307;
			
			// aapt resource value: 0x7f090020
			public const int btnBackToMain = 2131296288;
			
			// aapt resource value: 0x7f09002c
			public const int btnFollowListOpenMiniProfile = 2131296300;
			
			// aapt resource value: 0x7f09002f
			public const int btnFollowsListDoStuff = 2131296303;
			
			// aapt resource value: 0x7f09003d
			public const int btnMainBlockers = 2131296317;
			
			// aapt resource value: 0x7f090047
			public const int btnMainFans = 2131296327;
			
			// aapt resource value: 0x7f090037
			public const int btnMainFollowers = 2131296311;
			
			// aapt resource value: 0x7f09003a
			public const int btnMainFollowing = 2131296314;
			
			// aapt resource value: 0x7f09003f
			public const int btnMainGainedFollowers = 2131296319;
			
			// aapt resource value: 0x7f090041
			public const int btnMainLostFollowers = 2131296321;
			
			// aapt resource value: 0x7f090045
			public const int btnMainMutualFriends = 2131296325;
			
			// aapt resource value: 0x7f090043
			public const int btnMainNonFollowers = 2131296323;
			
			// aapt resource value: 0x7f090055
			public const int btnMiniProfileOpenInInstagram = 2131296341;
			
			// aapt resource value: 0x7f09001f
			public const int btnNewAccount = 2131296287;
			
			// aapt resource value: 0x7f090029
			public const int btnOK = 2131296297;
			
			// aapt resource value: 0x7f090034
			public const int btnRefresh = 2131296308;
			
			// aapt resource value: 0x7f09005a
			public const int cancel_action = 2131296346;
			
			// aapt resource value: 0x7f090009
			public const int center = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int center_horizontal = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int center_vertical = 2131296267;
			
			// aapt resource value: 0x7f090062
			public const int chronometer = 2131296354;
			
			// aapt resource value: 0x7f09000c
			public const int clip_horizontal = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int clip_vertical = 2131296269;
			
			// aapt resource value: 0x7f090023
			public const int customListViewAccounts = 2131296291;
			
			// aapt resource value: 0x7f09000e
			public const int end = 2131296270;
			
			// aapt resource value: 0x7f090069
			public const int end_padder = 2131296361;
			
			// aapt resource value: 0x7f09000f
			public const int fill = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int fill_horizontal = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int fill_vertical = 2131296273;
			
			// aapt resource value: 0x7f09001a
			public const int forever = 2131296282;
			
			// aapt resource value: 0x7f090064
			public const int icon = 2131296356;
			
			// aapt resource value: 0x7f090068
			public const int icon_group = 2131296360;
			
			// aapt resource value: 0x7f090024
			public const int imgAccountProfilePicture = 2131296292;
			
			// aapt resource value: 0x7f09002d
			public const int imgFollowListProfilePicture = 2131296301;
			
			// aapt resource value: 0x7f09001e
			public const int imgHeader = 2131296286;
			
			// aapt resource value: 0x7f090039
			public const int imgMainProfilePicture = 2131296313;
			
			// aapt resource value: 0x7f090052
			public const int imgMiniPostImage1 = 2131296338;
			
			// aapt resource value: 0x7f090053
			public const int imgMiniPostImage2 = 2131296339;
			
			// aapt resource value: 0x7f090054
			public const int imgMiniPostImage3 = 2131296340;
			
			// aapt resource value: 0x7f09004a
			public const int imgMiniProfilePicture = 2131296330;
			
			// aapt resource value: 0x7f090063
			public const int info = 2131296355;
			
			// aapt resource value: 0x7f09001b
			public const int italic = 2131296283;
			
			// aapt resource value: 0x7f090051
			public const int layoutMiniProfilePictures = 2131296337;
			
			// aapt resource value: 0x7f090012
			public const int left = 2131296274;
			
			// aapt resource value: 0x7f090000
			public const int line1 = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int line3 = 2131296257;
			
			// aapt resource value: 0x7f090036
			public const int linearLayoutUserInfo = 2131296310;
			
			// aapt resource value: 0x7f090022
			public const int lstAccounts = 2131296290;
			
			// aapt resource value: 0x7f09002b
			public const int lstFollows = 2131296299;
			
			// aapt resource value: 0x7f09005c
			public const int media_actions = 2131296348;
			
			// aapt resource value: 0x7f090016
			public const int none = 2131296278;
			
			// aapt resource value: 0x7f09001c
			public const int normal = 2131296284;
			
			// aapt resource value: 0x7f090066
			public const int notification_background = 2131296358;
			
			// aapt resource value: 0x7f09005f
			public const int notification_main_column = 2131296351;
			
			// aapt resource value: 0x7f09005e
			public const int notification_main_column_container = 2131296350;
			
			// aapt resource value: 0x7f090035
			public const int refreshLayout = 2131296309;
			
			// aapt resource value: 0x7f090013
			public const int right = 2131296275;
			
			// aapt resource value: 0x7f090065
			public const int right_icon = 2131296357;
			
			// aapt resource value: 0x7f090060
			public const int right_side = 2131296352;
			
			// aapt resource value: 0x7f090014
			public const int start = 2131296276;
			
			// aapt resource value: 0x7f09005b
			public const int status_bar_latest_event_content = 2131296347;
			
			// aapt resource value: 0x7f090002
			public const int tag_transition_group = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int tag_unhandled_key_event_manager = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int tag_unhandled_key_listeners = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int text = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int text2 = 2131296262;
			
			// aapt resource value: 0x7f090061
			public const int time = 2131296353;
			
			// aapt resource value: 0x7f090007
			public const int title = 2131296263;
			
			// aapt resource value: 0x7f090015
			public const int top = 2131296277;
			
			// aapt resource value: 0x7f090026
			public const int txtAccountFullName = 2131296294;
			
			// aapt resource value: 0x7f090025
			public const int txtAccountUsername = 2131296293;
			
			// aapt resource value: 0x7f090031
			public const int txtFollowListFollowingStatus = 2131296305;
			
			// aapt resource value: 0x7f090030
			public const int txtFollowListFullName = 2131296304;
			
			// aapt resource value: 0x7f09002e
			public const int txtFollowListUsername = 2131296302;
			
			// aapt resource value: 0x7f09002a
			public const int txtFollowsLayoutTitle = 2131296298;
			
			// aapt resource value: 0x7f09003e
			public const int txtMainBlockersCount = 2131296318;
			
			// aapt resource value: 0x7f090048
			public const int txtMainFansCount = 2131296328;
			
			// aapt resource value: 0x7f090038
			public const int txtMainFollowersCount = 2131296312;
			
			// aapt resource value: 0x7f09003b
			public const int txtMainFollowingCount = 2131296315;
			
			// aapt resource value: 0x7f090040
			public const int txtMainGainedFollowersCount = 2131296320;
			
			// aapt resource value: 0x7f090042
			public const int txtMainLostFollowersCount = 2131296322;
			
			// aapt resource value: 0x7f090046
			public const int txtMainMutualFriendsCount = 2131296326;
			
			// aapt resource value: 0x7f090044
			public const int txtMainNonFollowersCount = 2131296324;
			
			// aapt resource value: 0x7f09003c
			public const int txtMainUsername = 2131296316;
			
			// aapt resource value: 0x7f090028
			public const int txtMessage = 2131296296;
			
			// aapt resource value: 0x7f09004e
			public const int txtMiniProfileBio = 2131296334;
			
			// aapt resource value: 0x7f090049
			public const int txtMiniProfileFollowersCount = 2131296329;
			
			// aapt resource value: 0x7f09004b
			public const int txtMiniProfileFollowingCount = 2131296331;
			
			// aapt resource value: 0x7f09004d
			public const int txtMiniProfileFullName = 2131296333;
			
			// aapt resource value: 0x7f09004f
			public const int txtMiniProfilePostsCount = 2131296335;
			
			// aapt resource value: 0x7f090050
			public const int txtMiniProfilePostsStatus = 2131296336;
			
			// aapt resource value: 0x7f09004c
			public const int txtMiniProfileUsername = 2131296332;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int cancel_button_image_alpha = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int status_bar_notification_info_maxnum = 2131165185;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AccountsLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AccountsListView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CustomDialogLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int FollowsListLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int FollowsListView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int LoginLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MainLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int MiniProfileLayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int notification_action = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int notification_action_tombstone = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int notification_media_action = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int notification_media_cancel_action = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int notification_template_big_media = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int notification_template_big_media_custom = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int notification_template_big_media_narrow = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int notification_template_big_media_narrow_custom = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int notification_template_custom_big = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int notification_template_icon_group = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int notification_template_lines_media = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int notification_template_media = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int notification_template_media_custom = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int notification_template_part_chronometer = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int notification_template_part_time = 2130903063;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080002
			public const int ApplicationName = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int Hello = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int InstaClientId = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int InstaClientSecret = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int InstaRedirectURI = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int status_bar_notification_info_overflow = 2131230720;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f04000d
			public const int ActivityDialog = 2130968589;
			
			// aapt resource value: 0x7f040006
			public const int TextAppearance_Compat_Notification = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int TextAppearance_Compat_Notification_Info = 2130968583;
			
			// aapt resource value: 0x7f040000
			public const int TextAppearance_Compat_Notification_Info_Media = 2130968576;
			
			// aapt resource value: 0x7f04000c
			public const int TextAppearance_Compat_Notification_Line2 = 2130968588;
			
			// aapt resource value: 0x7f040004
			public const int TextAppearance_Compat_Notification_Line2_Media = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int TextAppearance_Compat_Notification_Media = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int TextAppearance_Compat_Notification_Time = 2130968584;
			
			// aapt resource value: 0x7f040002
			public const int TextAppearance_Compat_Notification_Time_Media = 2130968578;
			
			// aapt resource value: 0x7f040009
			public const int TextAppearance_Compat_Notification_Title = 2130968585;
			
			// aapt resource value: 0x7f040003
			public const int TextAppearance_Compat_Notification_Title_Media = 2130968579;
			
			// aapt resource value: 0x7f04000a
			public const int Widget_Compat_NotificationActionContainer = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int Widget_Compat_NotificationActionText = 2130968587;
			
			// aapt resource value: 0x7f040005
			public const int Widget_Support_CoordinatorLayout = 2130968581;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CircleImageView = new int[] {
					2130771989,
					2130771990,
					2130771991,
					2130771992};
			
			// aapt resource value: 1
			public const int CircleImageView_civ_border_color = 1;
			
			// aapt resource value: 2
			public const int CircleImageView_civ_border_overlay = 2;
			
			// aapt resource value: 0
			public const int CircleImageView_civ_border_width = 0;
			
			// aapt resource value: 3
			public const int CircleImageView_civ_fill_color = 3;
			
			public static int[] ColorStateListItem = new int[] {
					16843173,
					16843551,
					2130771977};
			
			// aapt resource value: 2
			public const int ColorStateListItem_alpha = 2;
			
			// aapt resource value: 1
			public const int ColorStateListItem_android_alpha = 1;
			
			// aapt resource value: 0
			public const int ColorStateListItem_android_color = 0;
			
			public static int[] CoordinatorLayout = new int[] {
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_keylines = 0;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_statusBarBackground = 1;
			
			public static int[] CoordinatorLayout_Layout = new int[] {
					16842931,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_Layout_android_layout_gravity = 0;
			
			// aapt resource value: 2
			public const int CoordinatorLayout_Layout_layout_anchor = 2;
			
			// aapt resource value: 4
			public const int CoordinatorLayout_Layout_layout_anchorGravity = 4;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_Layout_layout_behavior = 1;
			
			// aapt resource value: 6
			public const int CoordinatorLayout_Layout_layout_dodgeInsetEdges = 6;
			
			// aapt resource value: 5
			public const int CoordinatorLayout_Layout_layout_insetEdge = 5;
			
			// aapt resource value: 3
			public const int CoordinatorLayout_Layout_layout_keyline = 3;
			
			public static int[] FontFamily = new int[] {
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					16844143,
					16844144,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 4
			public const int FontFamilyFont_android_fontVariationSettings = 4;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public const int FontFamilyFont_android_ttcIndex = 3;
			
			// aapt resource value: 6
			public const int FontFamilyFont_font = 6;
			
			// aapt resource value: 5
			public const int FontFamilyFont_fontStyle = 5;
			
			// aapt resource value: 8
			public const int FontFamilyFont_fontVariationSettings = 8;
			
			// aapt resource value: 7
			public const int FontFamilyFont_fontWeight = 7;
			
			// aapt resource value: 9
			public const int FontFamilyFont_ttcIndex = 9;
			
			public static int[] GradientColor = new int[] {
					16843165,
					16843166,
					16843169,
					16843170,
					16843171,
					16843172,
					16843265,
					16843275,
					16844048,
					16844049,
					16844050,
					16844051};
			
			// aapt resource value: 7
			public const int GradientColor_android_centerColor = 7;
			
			// aapt resource value: 3
			public const int GradientColor_android_centerX = 3;
			
			// aapt resource value: 4
			public const int GradientColor_android_centerY = 4;
			
			// aapt resource value: 1
			public const int GradientColor_android_endColor = 1;
			
			// aapt resource value: 10
			public const int GradientColor_android_endX = 10;
			
			// aapt resource value: 11
			public const int GradientColor_android_endY = 11;
			
			// aapt resource value: 5
			public const int GradientColor_android_gradientRadius = 5;
			
			// aapt resource value: 0
			public const int GradientColor_android_startColor = 0;
			
			// aapt resource value: 8
			public const int GradientColor_android_startX = 8;
			
			// aapt resource value: 9
			public const int GradientColor_android_startY = 9;
			
			// aapt resource value: 6
			public const int GradientColor_android_tileMode = 6;
			
			// aapt resource value: 2
			public const int GradientColor_android_type = 2;
			
			public static int[] GradientColorItem = new int[] {
					16843173,
					16844052};
			
			// aapt resource value: 0
			public const int GradientColorItem_android_color = 0;
			
			// aapt resource value: 1
			public const int GradientColorItem_android_offset = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
